# Generated by Django 6.0.2 on 2026-02-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=50)),
                ('rep', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email'], name='pledge_pled_email_7ed0b2_idx')],
            },
        ),
    ]
