# Generated by Django 6.0.2 on 2026-03-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_senderemail'),
        ('pledge', '0002_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='contact',
            field=models.ForeignKey(blank=True, help_text='Optional link to unified contact record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='email_management.contact'),
        ),
        migrations.AddIndex(
            model_name='pledge',
            index=models.Index(fields=['contact'], name='pledge_pled_contact_dba015_idx'),
        ),
    ]
