# Generated by Django 6.0.2 on 2026-03-11 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioguide_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('party', models.CharField(choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=1)),
                ('state', models.CharField(max_length=2)),
                ('district', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('chamber', models.CharField(choices=[('house', 'House'), ('senate', 'Senate')], max_length=6)),
                ('in_office', models.BooleanField(default=True)),
                ('term_start', models.DateField(blank=True, null=True)),
                ('term_end', models.DateField(blank=True, null=True)),
                ('next_election', models.CharField(blank=True, default='', max_length=4)),
                ('seniority', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('official_website', models.URLField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('office_address', models.CharField(blank=True, default='', max_length=300)),
                ('contact_form_url', models.URLField(blank=True, default='')),
                ('twitter', models.CharField(blank=True, default='', max_length=100)),
                ('facebook', models.CharField(blank=True, default='', max_length=100)),
                ('youtube', models.CharField(blank=True, default='', max_length=100)),
                ('instagram', models.CharField(blank=True, default='', max_length=100)),
                ('opensecrets_id', models.CharField(blank=True, default='', max_length=20)),
                ('fec_ids', models.JSONField(blank=True, default=list)),
                ('govtrack_id', models.CharField(blank=True, default='', max_length=20)),
                ('votesmart_id', models.CharField(blank=True, default='', max_length=20)),
                ('alignment_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='BillPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_article', models.PositiveSmallIntegerField()),
                ('bill_title', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('sponsor', 'Sponsor'), ('cosponsor', 'Cosponsor'), ('voted_yes', 'Voted Yes'), ('voted_no', 'Voted No'), ('no_position', 'No Position')], default='no_position', max_length=15)),
                ('source_url', models.URLField(blank=True, default='')),
                ('last_checked', models.DateField(blank=True, null=True)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_positions', to='reps.representative')),
            ],
            options={
                'ordering': ['bill_article'],
                'unique_together': {('representative', 'bill_article')},
            },
        ),
    ]
