# Generated by Django 6.0.2 on 2026-03-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='narrative',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='representative',
            name='narrative_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
