# Generated by Django 6.0.2 on 2026-03-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reps', '0002_representative_narrative'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='narrative_sources',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
