# Generated by Django 6.0.2 on 2026-03-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenderEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Sender Email')),
                ('display_name', models.CharField(default='The 80% Bill', max_length=100, verbose_name='Display Name')),
                ('is_verified', models.BooleanField(default=False, help_text='Verified in email provider (Brevo, etc.)', verbose_name='Verified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.CharField(blank=True, help_text="e.g., 'General inquiries', 'Newsletter', 'Support'", max_length=255, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sender Email',
                'verbose_name_plural': 'Sender Emails',
                'ordering': ['-is_verified', 'email'],
            },
        ),
    ]
