# Generated by Django 6.0.2 on 2026-03-15 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_senderemail'),
        ('pledge', '0002_pledge_contact_pledge_pledge_pled_contact_dba015_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lists', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterModelTable(
            name='contactlist',
            table='contact_lists',
        ),
        migrations.CreateModel(
            name='ContactListMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='email_management.contact')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='email_management.contactlist')),
                ('pledge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to='pledge.pledge')),
            ],
            options={
                'db_table': 'contact_list_members',
                'indexes': [models.Index(fields=['contact'], name='contact_lis_contact_6e8fc1_idx'), models.Index(fields=['pledge'], name='contact_lis_pledge__7b3f0d_idx'), models.Index(fields=['list'], name='contact_lis_list_id_cd4019_idx')],
                'unique_together': {('list', 'contact'), ('list', 'pledge')},
            },
        ),
    ]
