# Generated by Django 6.0.2 on 2026-03-15 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0003_remove_contactlist_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Segment Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('definition', models.JSONField(default=dict, help_text='JSON filter rules for segment matching', verbose_name='Filter Definition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_segments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Segment',
                'verbose_name_plural': 'Segments',
                'db_table': 'segments',
                'ordering': ['-created_at'],
            },
        ),
    ]
