# Generated by Django 6.0.2 on 2026-03-15 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0005_replace_emailcampaign'),
        ('pledge', '0002_pledge_contact_pledge_pledge_pled_contact_dba015_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('scheduled_for', models.DateTimeField(blank=True, db_index=True, help_text='When this recipient is scheduled to receive the email', null=True, verbose_name='Scheduled For')),
                ('attempts', models.IntegerField(default=0, help_text='Number of send attempts', verbose_name='Attempts')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Failed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaign Recipient',
                'verbose_name_plural': 'Campaign Recipients',
                'db_table': 'campaign_recipients',
            },
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='email_campa_status_c9b1e2_idx',
            old_name='email_campa_status_0fd52f_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='email_campa_start_d_1b4534_idx',
            old_name='email_campa_start_d_c6e9cf_idx',
        ),
        migrations.RenameIndex(
            model_name='emailcampaign',
            new_name='email_campa_created_f7e9a0_idx',
            old_name='email_campa_created_5d9286_idx',
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='email_management.emailcampaign', verbose_name='Campaign'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='email_management.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_sends', to='pledge.pledge', verbose_name='Pledge'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['campaign', 'status'], name='campaign_re_campaig_6c3c85_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['status'], name='campaign_re_status_f95b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['scheduled_for'], name='campaign_re_schedul_069b33_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['contact'], name='campaign_re_contact_0f43bc_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrecipient',
            index=models.Index(fields=['pledge'], name='campaign_re_pledge__7af3b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignrecipient',
            unique_together={('campaign', 'contact'), ('campaign', 'pledge')},
        ),
    ]
