# Generated by Django 6.0.2 on 2026-03-15 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0006_campaignrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('html_body', models.TextField(verbose_name='HTML Body')),
                ('plain_body', models.TextField(blank=True, help_text='Fallback for email clients that do not support HTML', verbose_name='Plain Text Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about what changed in this version', verbose_name='Version Notes')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='email_management.emailcampaign', verbose_name='Campaign')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_versions', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Campaign Version',
                'verbose_name_plural': 'Campaign Versions',
                'db_table': 'campaign_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='campaignrecipient',
            name='campaign_version',
            field=models.ForeignKey(blank=True, help_text='The version of campaign content sent to this recipient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_sends', to='email_management.campaignversion', verbose_name='Campaign Version'),
        ),
        migrations.AddIndex(
            model_name='campaignversion',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_ve_campaig_82a525_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignversion',
            index=models.Index(fields=['created_at'], name='campaign_ve_created_6cebb3_idx'),
        ),
    ]
