"""
Django settings for the_80_percent_bill project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Always load .env from project root (works even when running from parent directory)
load_dotenv(BASE_DIR / ".env")

# Environment / secrets (loaded from .env or environment)
GEOCODIO_API_KEY = os.environ.get("GEOCODIO_API_KEY", "")
EMAIL_PASSWORD = os.environ.get("EMAIL_PASSWORD", "")
DONATION_LINK = "https://www.buymeacoffee.com/80percentbill"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-@xax3!&6)_c_d31&m)_wr0u&s7oovcwo4%4wg35zlxer=ch_ko")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "the80percentbill.com",
    ".the80percentbill.com",
    ".railway.app",
    ".up.railway.app",
]
if extra_hosts := os.environ.get("ALLOWED_HOSTS"):
    ALLOWED_HOSTS.extend(h.strip() for h in extra_hosts.split(",") if h.strip())


# Application definition

INSTALLED_APPS = [
    "core",
    "home",
    "bill",
    "pledge",
    "django.contrib.admin",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'the_80_percent_bill.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'the_80_percent_bill.context_processors.site_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'the_80_percent_bill.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_password = os.environ.get("SUPABASE_DB_PASSWORD")
if _db_password:
    # Use pooler (Supavisor) for IPv4 compatibility — Railway and many hosts lack IPv6.
    # Direct connection (db.xxx.supabase.co) resolves to IPv6 and fails with "Network unreachable".
    # Get pooler strings from Supabase Dashboard → Project → Connect → Session or Transaction.
    _use_pooler = os.environ.get("SUPABASE_USE_POOLER", "true").lower() in ("true", "1", "yes")
    if _use_pooler:
        # Session mode (port 5432): IPv4-compatible, supports prepared statements. Best for Django.
        # User must be postgres.<PROJECT_REF> — get from Supabase Connect → Session pooler.
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("SUPABASE_DB_NAME", "postgres"),
                "USER": os.environ.get("SUPABASE_DB_USER", "postgres.dugqtfasgcprvqpcktdl"),
                "PASSWORD": _db_password,
                "HOST": os.environ.get("SUPABASE_DB_HOST", "aws-0-us-east-1.pooler.supabase.com"),
                "PORT": os.environ.get("SUPABASE_DB_PORT", "5432"),
                "OPTIONS": {"sslmode": "require"},
            }
        }
    else:
        # Direct connection (IPv6 only — fails on Railway)
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("SUPABASE_DB_NAME", "postgres"),
                "USER": os.environ.get("SUPABASE_DB_USER", "postgres"),
                "PASSWORD": _db_password,
                "HOST": os.environ.get("SUPABASE_DB_HOST", "db.dugqtfasgcprvqpcktdl.supabase.co"),
                "PORT": os.environ.get("SUPABASE_DB_PORT", "5432"),
                "OPTIONS": {"sslmode": "require"},
            }
        }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
